version: '2'
services:
  postgres:
    container_name: postgres-omxs
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=dai
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
      - "9113"
    ports:
      - "5434:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      postgres:

networks:
    postgres:
    
